pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'ls'
                sh 'cd Multibranch && npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'cd Multibranch && ./jenkins/scripts/test.sh'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
                sh 'cd Multibranch && ./jenkins/scripts/deliver-for-development.sh'
                
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'cd Multibranch && ./jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'production'
            }
            steps {
                sh 'cd Multibranch && ./jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'cd Multibranch && ./jenkins/scripts/kill.sh'
            }
        }
    }
}
